name: Trigger auto deployment for poj-perf

on:
  push:
    branches: 
      [ main ]
    paths:
    - 'backend/**'
    - '.github/workflows/poj-perf-AutoDeployTrigger-a2f57005-9797-45f7-b6df-e93ff24e9657.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.POJPERF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.POJPERF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.POJPERF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: Dockerfile  # Relative to appSourcePath
          registryUrl: 
          registryUsername: ${{ secrets.POJPERF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POJPERF_REGISTRY_PASSWORD }}
          containerAppName: poj-perf
          resourceGroup: poj-perf-rg
          imageToBuild: default/poj-perf:${{ github.sha }}
          targetPort: 8000